#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l walltime=24:00:00
#PBS -l mem=40GB
#PBS -N genTree_5e-7D_Dbe
#PBS -M justinmaojones@nyu.edu
#PBS -j oe

# load necessary modules

module purge
module load python/intel/2.7.6
module load graph-tool/gnu/2.2.42

# define location of working directory when the HPC gets going

# run source code
# location of the source code must be defined explicitly
SOURCEDIR=$HOME/Sloth/graph-tool
cd $SOURCEDIR
python generateTree.py '5e-7D'
